name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v4
        
      # 安装 Wrangler
      - name: Install Wrangler
        run: npm install -g wrangler@3.99.0

      # 部署到 Cloudflare Workers
      - name: Deploy to Cloudflare
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          TODAY=$(date +%Y-%m-%d)
          npx wrangler deploy index.js --name gh --compatibility-date $TODAY

