name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 安装 Wrangler
      - name: Install Wrangler
        run: npm install -g wrangler@3.99.0

      # 部署到 Cloudflare Workers
      - name: Deploy to Cloudflare
        env:
          CF_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: npx wrangler deploy index.js --account-id ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

